# Test Data Feature Extraction

### Adding actors and directors data to test data

In [133]:
import numpy as np
import pandas as pd

In [134]:
test_file = 'data/test_data.csv'
test_data = pd.read_csv(test_file)

In [135]:
actors_csv = 'data/BollywoodActorRanking.csv'
directors_csv = 'data/BollywoodDirectorRanking.csv'
actors_df = pd.read_csv(actors_csv)
directors_df = pd.read_csv(directors_csv)

In [136]:
test_data

title  releaseYear   releaseDate genre_x  \
0            Newton         2017   22 Sep 2017   drama   
1      Hindi Medium         2017   19 May 2017  comedy   
2       Jolly LLB 2         2017   10 Feb 2017  comedy   
3            Toilet         2017     11Aug2017   drama   
4        Bahubali 2         2017   28April2017   drama   
5             Raees         2017   25 Jan 2017  action   
6  Secret superstar         2017   19 Oct 2017   drama   
7      Jagga jasoos         2017  14 July 2017   drama   
8         Tubelight         2017   23June 2017   drama   

                          writers  \
0    Amit Masurkar  Mayank Tewari   
1  Saket Chaudhary Zeenat Lakhani   
2                  Subhash Kapoor   
3                   Hitesh Thakur   
4           K.V.Vijayendra Prasad   
5                  Rahul dholakia   
6                  Adviat Chandan   
7                     Anurag basu   
8                      Kabir khan   

                                              actors            directors  \
0       Rajkummar Rao, Pankaj Tripathi, Anjali Patil        Amit Masurkar   
1            Saba Qamar, Irrfan Khan, Sanjana Sanghi      Saket Chaudhary   
2         Akshay Kumar, Huma Qureshi, Saurabh Shukla       Subhash Kapoor   
3  Akshay Kumar,Bhumi Pednekar,Divyendu Sharma,An...  Shree narayan singh   
4  Prabhash,Rana daggubati,Anushka Shetty,Tamanna...         S.S rajmouli   
5    Shahrukh khan, Nawazuddin siddiqui, Mahira khan       Rahul dholakia   
6                            Zaira Wasim, Aamir khan        Advit Chandan   
7                         Ranbir kapoor,Katrina kaif          Anurag basu   
8                           Salman khan, sohail khan           Kabir khan   

   sequel  hitFlop        movie_name       ...       screens     footfall  \
0       0      8.0            Newton       ...           450    18,25,000   
1       0      8.0      Hindi Medium       ...          1050    54,72,000   
2       1      7.0       Jolly LLB 2       ...          3300  1,16,53,000   
3       0      NaN            Toilet       ...          2950  1,31,35,000   
4       1      NaN        Bahubali 2       ...          3950  5,25,22,000   
5       0      NaN             Raees       ...          3400  1,37,82,000   
6       0      NaN  Secret superstar       ...          1750    50,87,000   
7       0      NaN      Jagga jasoos       ...          1750    49,74,000   
8       0      NaN         Tubelight       ...          4400  1,15,74,000   

           budget     first_day   first_weekend      first_week  \
0     9,00,00,000     93,00,000     6,81,00,000    11,64,00,000   
1    23,00,00,000   2,50,00,000    11,79,00,000    23,25,00,000   
2    83,00,00,000  12,06,00,000    47,59,00,000    73,58,00,000   
3    75,00,00,000  11,34,00,000    49,09,00,000    94,21,00,000   
4  1,95,00,00,000  40,73,00,000  1,27,28,00,000  2,46,47,00,000   
5  1,27,00,00,000  20,29,00,000    69,48,00,000  1,02,00,00,000   
6    45,00,00,000   4,77,00,000    22,56,00,000    38,67,00,000   
7  1,31,00,00,000   8,21,00,000    31,53,00,000    43,12,00,000   
8  1,35,00,00,000  20,55,00,000    61,53,00,000  1,02,57,00,000   

  worldwide_first_week worldwide_first_weekend     india_gross worldwide_gross  
0         15,24,84,000             8,92,11,000    29,12,00,000    29,12,00,000  
1         29,32,00,000            21,99,25,000    77,61,00,000    91,85,50,000  
2       1,25,14,12,000            83,16,43,500  1,49,58,00,000  1,82,73,42,500  
3         75,52,83,000          1,38,65,47,000  1,68,08,00,000  2,00,08,00,000  
4       2,09,68,52,000          3,88,83,98,000  7,08,99,00,000  8,01,61,20,000  
5       1,28,13,56,000          2,04,68,00,000  1,76,64,00,000  2,72,52,00,000  
6         46,32,74,000            74,19,43,000    81,00,00,000  1,22,53,50,000  
7         69,86,84,000            51,20,26,000    69,31,00,000    86,85,72,500  
8       1,08,61,26,000          1,78,89,84,000  1,56,39,00,000  2,07,99,00,000  

[9 rows x 24 columns]

In [137]:
test_data['actors'] = test_data['actors'].str.split(',')
test_data['actors'].values

array([list(['Rajkummar Rao', ' Pankaj Tripathi', ' Anjali Patil']),
       list(['Saba Qamar', ' Irrfan Khan', ' Sanjana Sanghi']),
       list(['Akshay Kumar', ' Huma Qureshi', ' Saurabh Shukla']),
       list(['Akshay Kumar', 'Bhumi Pednekar', 'Divyendu Sharma', 'Anupum kher']),
       list(['Prabhash', 'Rana daggubati', 'Anushka Shetty', 'Tamanna bhatia']),
       list(['Shahrukh khan', ' Nawazuddin siddiqui', ' Mahira khan']),
       list(['Zaira Wasim', ' Aamir khan']),
       list(['Ranbir kapoor', 'Katrina kaif']),
       list(['Salman khan', ' sohail khan'])], dtype=object)

In [138]:
test_data['actors'].values

array([list(['Rajkummar Rao', ' Pankaj Tripathi', ' Anjali Patil']),
       list(['Saba Qamar', ' Irrfan Khan', ' Sanjana Sanghi']),
       list(['Akshay Kumar', ' Huma Qureshi', ' Saurabh Shukla']),
       list(['Akshay Kumar', 'Bhumi Pednekar', 'Divyendu Sharma', 'Anupum kher']),
       list(['Prabhash', 'Rana daggubati', 'Anushka Shetty', 'Tamanna bhatia']),
       list(['Shahrukh khan', ' Nawazuddin siddiqui', ' Mahira khan']),
       list(['Zaira Wasim', ' Aamir khan']),
       list(['Ranbir kapoor', 'Katrina kaif']),
       list(['Salman khan', ' sohail khan'])], dtype=object)

In [139]:
actor_data = list()
for actors in test_data['actors']:
    actors = [s.strip() for s in actors]
    new_df = actors_df.loc[actors_df['actorName'].isin(actors)]
    actor_data.append([new_df['movieCount'].mean(), new_df['ratingSum'].mean(), new_df['normalizedMovieRank'].mean(), new_df['googleHits'].mean(), new_df['normalizedGoogleRank'].mean(), new_df['normalizedRating'].mean()])
print(actor_data)

[[4.0, 290.0, 6.1358699798583975, 0.0, nan, 3.92707991600037], [21.0, 780.0, 2.677020072937012, 268000.0, 1.6879500150680542, 2.91778993606567], [32.0, 1685.0, 3.7699249982833862, 1031000.0, 3.6563249230384827, 4.66250491142273], [54.0, 2950.0, 4.3876800537109375, 1960000.0, 6.0529398918151855, 6.38047981262207], [nan, nan, nan, nan, nan, nan], [nan, nan, nan, nan, nan, nan], [nan, nan, nan, nan, nan, nan], [nan, nan, nan, nan, nan, nan], [nan, nan, nan, nan, nan, nan]]


In [140]:
actor_data = pd.DataFrame(data=actor_data, columns=['actors_movieCount', 'actors_ratingSum', 'actors_normalizedMovieRank',
                'actors_googleHits', 'actors_normalizedGoogleRank', 'actors_normalizedRating'])

In [141]:
actor_data = actor_data.fillna(actor_data.mean())
actor_data

actors_movieCount  actors_ratingSum  actors_normalizedMovieRank  \
0               4.00            290.00                    6.135870   
1              21.00            780.00                    2.677020   
2              32.00           1685.00                    3.769925   
3              54.00           2950.00                    4.387680   
4              27.75           1426.25                    4.242624   
5              27.75           1426.25                    4.242624   
6              27.75           1426.25                    4.242624   
7              27.75           1426.25                    4.242624   
8              27.75           1426.25                    4.242624   

   actors_googleHits  actors_normalizedGoogleRank  actors_normalizedRating  
0                0.0                     3.799072                 3.927080  
1           268000.0                     1.687950                 2.917790  
2          1031000.0                     3.656325                 4.662505  
3          1960000.0                     6.052940                 6.380480  
4           814750.0                     3.799072                 4.471964  
5           814750.0                     3.799072                 4.471964  
6           814750.0                     3.799072                 4.471964  
7           814750.0                     3.799072                 4.471964  
8           814750.0                     3.799072                 4.471964

In [142]:
test_data['directors'] = test_data['directors'].str.split(', ')
test_data['directors']

0          [Amit Masurkar]
1        [Saket Chaudhary]
2         [Subhash Kapoor]
3    [Shree narayan singh]
4           [S.S rajmouli]
5         [Rahul dholakia]
6          [Advit Chandan]
7            [Anurag basu]
8             [Kabir khan]
Name: directors, dtype: object

In [143]:
director_data = list()
for directors in test_data['directors']:
    directors = [s.strip() for s in directors]
    new_df = directors_df.loc[directors_df['directorName'].isin(directors)]
    director_data.append([new_df['movieCount'].mean(), new_df['ratingSum'].mean(), new_df['normalizedMovieRank'].mean(), new_df['googleHits'].mean(), new_df['normalizedGoogleRank'].mean(), new_df['normalizedRating'].mean()])
print(director_data)

[[nan, nan, nan, nan, nan, nan], [nan, nan, nan, nan, nan, nan], [nan, nan, nan, nan, nan, nan], [nan, nan, nan, nan, nan, nan], [nan, nan, nan, nan, nan, nan], [nan, nan, nan, nan, nan, nan], [nan, nan, nan, nan, nan, nan], [nan, nan, nan, nan, nan, nan], [nan, nan, nan, nan, nan, nan]]


In [144]:
director_data = pd.DataFrame(data=director_data, columns=['movieCount', 'ratingSum', 'normalizedMovieRank',
                'googleHits', 'normalizedGoogleRank', 'normalizedRating'])
director_data

movieCount  ratingSum  normalizedMovieRank  googleHits  \
0         NaN        NaN                  NaN         NaN   
1         NaN        NaN                  NaN         NaN   
2         NaN        NaN                  NaN         NaN   
3         NaN        NaN                  NaN         NaN   
4         NaN        NaN                  NaN         NaN   
5         NaN        NaN                  NaN         NaN   
6         NaN        NaN                  NaN         NaN   
7         NaN        NaN                  NaN         NaN   
8         NaN        NaN                  NaN         NaN   

   normalizedGoogleRank  normalizedRating  
0                   NaN               NaN  
1                   NaN               NaN  
2                   NaN               NaN  
3                   NaN               NaN  
4                   NaN               NaN  
5                   NaN               NaN  
6                   NaN               NaN  
7                   NaN               NaN  
8                   NaN               NaN

In [156]:
new_list = list()
for l in directors_df.iloc[0:9, 2:].values:
    new_list.append(l)
new_list

[array([3.00000000e+00, 4.40000000e+02, 1.00000000e+01, 1.46000000e+05,
        2.07796001e+00, 1.00000000e+01]),
 array([4.00000000e+00, 4.40000000e+02, 7.39474010e+00, 1.06000000e+06,
        8.88317013e+00, 8.78472996e+00]),
 array([5.00000000e+00, 4.30000000e+02, 5.68946981e+00, 1.05000000e+06,
        8.80871964e+00, 7.10459995e+00]),
 array([4.00000000e+00, 3.50000000e+02, 5.79605007e+00, 9.05000000e+05,
        7.72911978e+00, 6.99779987e+00]),
 array([1.00000000e+01, 9.50000000e+02, 6.32894993e+00, 4.37000000e+05,
        4.24460983e+00, 6.83760977e+00]),
 array([3.00000000e+00, 2.70000000e+02, 5.97368002e+00, 6.66000000e+05,
        5.94963980e+00, 6.82367992e+00]),
 array([6.00000000e+00, 3.90000000e+02, 4.19737005e+00, 1.11000000e+06,
        9.25545025e+00, 5.73446989e+00]),
 array([4.00000000e+00, 2.90000000e+02, 4.73025990e+00, 7.42000000e+05,
        6.51549006e+00, 5.71972990e+00]),
 array([5.00000000e+00, 4.00000000e+02, 5.26316023e+00, 3.12000000e+05,
        3.313920

In [157]:
len(new_list)

9

In [158]:
director_data.loc[(director_data.isnull().all(axis=1))] = new_list
director_data

movieCount  ratingSum  normalizedMovieRank  googleHits  \
0         3.0      440.0             10.00000    146000.0   
1         4.0      440.0              7.39474   1060000.0   
2         5.0      430.0              5.68947   1050000.0   
3         4.0      350.0              5.79605    905000.0   
4        10.0      950.0              6.32895    437000.0   
5         3.0      270.0              5.97368    666000.0   
6         6.0      390.0              4.19737   1110000.0   
7         4.0      290.0              4.73026    742000.0   
8         5.0      400.0              5.26316    312000.0   

   normalizedGoogleRank  normalizedRating  
0               2.07796          10.00000  
1               8.88317           8.78473  
2               8.80872           7.10460  
3               7.72912           6.99780  
4               4.24461           6.83761  
5               5.94964           6.82368  
6               9.25545           5.73447  
7               6.51549           5.71973  
8               3.31392           5.61481

In [159]:
director_data.columns = ['directors_' + str(col) for col in director_data.columns]
director_data

directors_movieCount  directors_ratingSum  directors_normalizedMovieRank  \
0                   3.0                440.0                       10.00000   
1                   4.0                440.0                        7.39474   
2                   5.0                430.0                        5.68947   
3                   4.0                350.0                        5.79605   
4                  10.0                950.0                        6.32895   
5                   3.0                270.0                        5.97368   
6                   6.0                390.0                        4.19737   
7                   4.0                290.0                        4.73026   
8                   5.0                400.0                        5.26316   

   directors_googleHits  directors_normalizedGoogleRank  \
0              146000.0                         2.07796   
1             1060000.0                         8.88317   
2             1050000.0                         8.80872   
3              905000.0                         7.72912   
4              437000.0                         4.24461   
5              666000.0                         5.94964   
6             1110000.0                         9.25545   
7              742000.0                         6.51549   
8              312000.0                         3.31392   

   directors_normalizedRating  
0                    10.00000  
1                     8.78473  
2                     7.10460  
3                     6.99780  
4                     6.83761  
5                     6.82368  
6                     5.73447  
7                     5.71973  
8                     5.61481

In [160]:
test_data = test_data.join(actor_data)
test_data = test_data.join(director_data)
test_data

title  releaseYear   releaseDate genre_x  \
0            Newton         2017   22 Sep 2017   drama   
1      Hindi Medium         2017   19 May 2017  comedy   
2       Jolly LLB 2         2017   10 Feb 2017  comedy   
3            Toilet         2017     11Aug2017   drama   
4        Bahubali 2         2017   28April2017   drama   
5             Raees         2017   25 Jan 2017  action   
6  Secret superstar         2017   19 Oct 2017   drama   
7      Jagga jasoos         2017  14 July 2017   drama   
8         Tubelight         2017   23June 2017   drama   

                          writers  \
0    Amit Masurkar  Mayank Tewari   
1  Saket Chaudhary Zeenat Lakhani   
2                  Subhash Kapoor   
3                   Hitesh Thakur   
4           K.V.Vijayendra Prasad   
5                  Rahul dholakia   
6                  Adviat Chandan   
7                     Anurag basu   
8                      Kabir khan   

                                              actors              directors  \
0   [Rajkummar Rao,  Pankaj Tripathi,  Anjali Patil]        [Amit Masurkar]   
1        [Saba Qamar,  Irrfan Khan,  Sanjana Sanghi]      [Saket Chaudhary]   
2     [Akshay Kumar,  Huma Qureshi,  Saurabh Shukla]       [Subhash Kapoor]   
3  [Akshay Kumar, Bhumi Pednekar, Divyendu Sharma...  [Shree narayan singh]   
4  [Prabhash, Rana daggubati, Anushka Shetty, Tam...         [S.S rajmouli]   
5  [Shahrukh khan,  Nawazuddin siddiqui,  Mahira ...       [Rahul dholakia]   
6                         [Zaira Wasim,  Aamir khan]        [Advit Chandan]   
7                      [Ranbir kapoor, Katrina kaif]          [Anurag basu]   
8                        [Salman khan,  sohail khan]           [Kabir khan]   

   sequel  hitFlop        movie_name            ...              \
0       0      8.0            Newton            ...               
1       0      8.0      Hindi Medium            ...               
2       1      7.0       Jolly LLB 2            ...               
3       0      NaN            Toilet            ...               
4       1      NaN        Bahubali 2            ...               
5       0      NaN             Raees            ...               
6       0      NaN  Secret superstar            ...               
7       0      NaN      Jagga jasoos            ...               
8       0      NaN         Tubelight            ...               

  actors_normalizedMovieRank actors_googleHits actors_normalizedGoogleRank  \
0                   6.135870               0.0                    3.799072   
1                   2.677020          268000.0                    1.687950   
2                   3.769925         1031000.0                    3.656325   
3                   4.387680         1960000.0                    6.052940   
4                   4.242624          814750.0                    3.799072   
5                   4.242624          814750.0                    3.799072   
6                   4.242624          814750.0                    3.799072   
7                   4.242624          814750.0                    3.799072   
8                   4.242624          814750.0                    3.799072   

  actors_normalizedRating  directors_movieCount directors_ratingSum  \
0                3.927080                   3.0               440.0   
1                2.917790                   4.0               440.0   
2                4.662505                   5.0               430.0   
3                6.380480                   4.0               350.0   
4                4.471964                  10.0               950.0   
5                4.471964                   3.0               270.0   
6                4.471964                   6.0               390.0   
7                4.471964                   4.0               290.0   
8                4.471964                   5.0               400.0   

  directors_normalizedMovieRank directors_googleHits  \
0                      10.00000             146000.0

In [161]:
test_data.to_csv('data/final_test_data.csv')